# Generated by Django 6.0 on 2026-05-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_meal_mealcategory_user_email_verified_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
