# Generated by Django 6.0 on 2026-05-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_meal_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='allergens',
        ),
        migrations.AddField(
            model_name='meal',
            name='allergens_json',
            field=models.TextField(default='[]', help_text='JSON-formatted list of allergens'),
        ),
    ]
